### ISSUE TITLE
Application Grading Requirements

### ISSUE THREAD

**Issue by marina-russ** [Fiskoal/astroplanner#1]
Your project should fulfill the following requirements:

- [x] Use a CSS framework other than Bootstrap.
- [x] Be deployed to GitHub Pages.
- [x] Be interactive (i.e., accept and respond to user input).
- [x] Use at least two server-side APIs.
- [x] Does not use alerts, confirms, or prompts (use modals).
- [x] Use client-side storage to store persistent data.
- [x] Be responsive.
- [x] Have a polished UI.
- [x] Have a clean repository that meets quality coding standards (file structure, naming conventions, follows best practices for class/id naming conventions, indentation, quality comments, etc.).
- [x] Have a quality README (with unique name, description, technologies used, screenshot, and link to deployed application).

**Comment by Fiskoal** [comment]
very cool
